### ISSUE TITLE
Tomar screenshots de iAuditor

### ISSUE THREAD

**Issue by fmendoza-gstd** [globalstandards/gpsi-audit-android#1]
Tomar capturas de pantalla de las vistas más importantes de la aplicación y adjuntarlas sobre esta tarjeta.

**Comment by gvazquez-gstd** [comment]
![1-intro](https://cloud.githubusercontent.com/assets/22351269/23384669/a5222d82-fd11-11e6-9098-e2c8eb8d1c2d.png)
![2-login](https://cloud.githubusercontent.com/assets/22351269/23384674/a52bdac6-fd11-11e6-8f6c-b6b1516533d7.png)
![2-login_1](https://cloud.githubusercontent.com/assets/22351269/23384670/a5278656-fd11-11e6-8db0-05bd3bd8d34c.png)
![3-crear cuenta](https://cloud.githubusercontent.com/assets/22351269/23384673/a5288dda-fd11-11e6-8488-e4fcfd794184.png)
![3-crear cuenta_1](https://cloud.githubusercontent.com/assets/22351269/23384671/a527cda0-fd11-11e6-84a3-ee24777530a2.png)
![4-main](https://cloud.githubusercontent.com/assets/22351269/23384672/a5287d90-fd11-11e6-88e2-787b90f26172.png)
![4-main_1](https://cloud.githubusercontent.com/assets/22351269/23384675/a53fcd2e-fd11-11e6-8c1f-2e2e019cd111.png)
![5-presentacion_1](https://cloud.githubusercontent.com/assets/22351269/23384676/a544c0a4-fd11-11e6-9d39-abf0bd22b30c.png)
![5-presentacion_2](https://cloud.githubusercontent.com/assets/22351269/23384681/a5506792-fd11-11e6-83d2-eb840bdb1e29.png)
![5-presentacion_3](https://cloud.githubusercontent.com/assets/22351269/23384678/a546a66c-fd11-11e6-9d2f-3a76325153ac.png)
![5-presentacion_4](https://cloud.githubusercontent.com/assets/22351269/23384679/a5481c54-fd11-11e6-963b-904075f5b267.png)
![5-presentacion_5](https://cloud.githubusercontent.com/assets/22351269/23384680/a548d02c-fd11-11e6-9d48-9818cbd46213.png)
![5-presentacion_6](https://cloud.githubusercontent.com/assets/22351269/23384682/a55bf602-fd11-11e6-89ce-d19357211834.png)
![5-presentacion_7](https://cloud.githubusercontent.com/assets/22351269/23384683/a561139e-fd11-11e6-9fd7-d32a2cf7756c.png)
![5-presentacion_8](https://cloud.githubusercontent.com/assets/22351269/23384685/a581b1c6-fd11-11e6-935c-9f5bcb768137.png)
![5-presentacion_9](https://cloud.githubusercontent.com/assets/22351269/23384684/a580fc54-fd11-11e6-811a-38fd5e9f4590.png)
![5-presentacion_10](https://cloud.githubusercontent.com/assets/22351269/23384686/a58efb9c-fd11-11e6-90ab-473d23b189f3.png)
![5-presentacion_11](https://cloud.githubusercontent.com/assets/22351269/23384687/a5920bc0-fd11-11e6-9dba-c1715177fd17.png)
![6-auditorias](https://cloud.githubusercontent.com/assets/22351269/23384689/a5a9ffe6-fd11-11e6-91e9-3ff4fc892b0b.png)
![7-biblioteca publica_1](https://cloud.githubusercontent.com/assets/22351269/23384690/a5aa13a0-fd11-11e6-8bb0-d900b2387435.png)
![7-biblioteca publica_2](https://cloud.githubusercontent.com/assets/22351269/23384688/a5a42774-fd11-11e6-9989-6e703183ac44.png)
![8-programa_1](https://cloud.githubusercontent.com/assets/22351269/23384691/a5ad137a-fd11-11e6-9bb9-2878a3bb1e23.png)
![8-programa_2](https://cloud.githubusercontent.com/assets/22351269/23384692/a5afa72a-fd11-11e6-9c82-3f843e8f2d29.png)
![8-programa_3](https://cloud.githubusercontent.com/assets/22351269/23384693/a5b3ae56-fd11-11e6-8ef4-f5ecf035dfd0.png)
![8-programa_4](https://cloud.githubusercontent.com/assets/22351269/23384695/a5cbd300-fd11-11e6-9096-19e0bd2448af.png)
![8-programa_5](https://cloud.githubusercontent.com/assets/22351269/23384699/a5d8a512-fd11-11e6-9723-96133ebb33ff.png)
![8-programa_6](https://cloud.githubusercontent.com/assets/22351269/23384694/a5cb7bee-fd11-11e6-9a46-d712cbd69058.png)
![8-programa_7](https://cloud.githubusercontent.com/assets/22351269/23384696/a5d3380c-fd11-11e6-8988-9e120f634ad8.png)
![8-programa_8](https://cloud.githubusercontent.com/assets/22351269/23384698/a5d7c37c-fd11-11e6-9c07-621312ba651c.png)
![8-programa_9](https://cloud.githubusercontent.com/assets/22351269/23384697/a5d570cc-fd11-11e6-8c71-598e8061face.png)
![8-programa_10](https://cloud.githubusercontent.com/assets/22351269/23384700/a5eac4b8-fd11-11e6-8774-53d9ecba61db.png)
![8-programa_11](https://cloud.githubusercontent.com/assets/22351269/23384701/a5eaf1ea-fd11-11e6-9fc7-e1da9a48dc4a.png)
![8-programa_12](https://cloud.githubusercontent.com/assets/22351269/23384704/a5fce9ae-fd11-11e6-9ec9-04851ff169d2.png)
![8-programa_13](https://cloud.githubusercontent.com/assets/22351269/23384702/a5f31c1c-fd11-11e6-88ff-bc1001b7aa4a.png)
![8-programa_14](https://cloud.githubusercontent.com/assets/22351269/23384703/a5f6e6da-fd11-11e6-917f-e6ae188422ea.png)
![8-programa_15](https://cloud.githubusercontent.com/assets/22351269/23384706/a61189c2-fd11-11e6-88b0-94df02727a89.png)
![8-programa_16](https://cloud.githubusercontent.com/assets/22351269/23384705/a6098c0e-fd11-11e6-94b4-11e576e16e3e.png)
![8-programa_17](https://cloud.githubusercontent.com/assets/22351269/23384707/a6142c90-fd11-11e6-9300-b94a62210c84.png)
![8-programa_18](https://cloud.githubusercontent.com/assets/22351269/23384710/a6203508-fd11-11e6-9b95-c05f2292be06.png)
![8-programa_19](https://cloud.githubusercontent.com/assets/22351269/23384708/a61b3030-fd11-11e6-8ebd-8cfffdbd0d21.png)
![8-programa_20](https://cloud.githubusercontent.com/assets/22351269/23384709/a61e4ba8-fd11-11e6-8da7-e8297833b2d9.png)
![8-programa_21](https://cloud.githubusercontent.com/assets/22351269/23384711/a6264ccc-fd11-11e6-8b4e-95b3599c95bc.png)
![8-programa_22](https://cloud.githubusercontent.com/assets/22351269/23384712/a6336664-fd11-11e6-8726-6152ec6acad8.png)
![8-programa_23](https://cloud.githubusercontent.com/assets/22351269/23384713/a638d734-fd11-11e6-8d5f-4e217a900e93.png)
![8-programa_24](https://cloud.githubusercontent.com/assets/22351269/23384715/a63eb000-fd11-11e6-805e-f1e733de1fd6.png)
![8-programa_25](https://cloud.githubusercontent.com/assets/22351269/23384716/a6419a86-fd11-11e6-88b5-fcf88007ab62.png)
![8-programa_26](https://cloud.githubusercontent.com/assets/22351269/23384717/a6420e6c-fd11-11e6-8992-2a0d61858ab3.png)
![8-programa_27](https://cloud.githubusercontent.com/assets/22351269/23384718/a643af60-fd11-11e6-80b6-8e34bb55fe9a.png)
![8-programa_28](https://cloud.githubusercontent.com/assets/22351269/23384719/a6506be2-fd11-11e6-9499-845e4980edd4.png)
![8-programa_29](https://cloud.githubusercontent.com/assets/22351269/23384722/a66147e6-fd11-11e6-999a-88f5e3e58f19.png)
![8-programa_30](https://cloud.githubusercontent.com/assets/22351269/23384721/a6610e8e-fd11-11e6-979d-bee6ed9118c5.png)
![8-programa_31](https://cloud.githubusercontent.com/assets/22351269/23384720/a6605584-fd11-11e6-95ba-6b8f99c56456.png)
![8-programa_32](https://cloud.githubusercontent.com/assets/22351269/23384723/a6627468-fd11-11e6-8105-ad63ab57f7f7.png)
![8-programa_33](https://cloud.githubusercontent.com/assets/22351269/23384724/a6697be6-fd11-11e6-96c2-c8221090aebf.png)
![8-programa_34](https://cloud.githubusercontent.com/assets/22351269/23384725/a6708486-fd11-11e6-83fa-1b05aebab3c9.png)
![8-programa_35](https://cloud.githubusercontent.com/assets/22351269/23384726/a681d4b6-fd11-11e6-97c1-3a6d8e6733b8.png)
![8-programa_36](https://cloud.githubusercontent.com/assets/22351269/23384727/a6848760-fd11-11e6-858c-c799af11ff23.png)
![8-programa_37](https://cloud.githubusercontent.com/assets/22351269/23384728/a688728a-fd11-11e6-9463-7b5ffbd90cb6.png)
![8-programa_38](https://cloud.githubusercontent.com/assets/22351269/23384729/a6893c24-fd11-11e6-8c68-c324fdf73ecf.png)
![8-programa_39](https://cloud.githubusercontent.com/assets/22351269/23384730/a6893864-fd11-11e6-84db-64d241b2d263.png)
![8-programa_40](https://cloud.githubusercontent.com/assets/22351269/23384731/a68de3dc-fd11-11e6-99c4-5874bda5334c.png)
![8-programa_41](https://cloud.githubusercontent.com/assets/22351269/23384734/a6a5aac6-fd11-11e6-907e-2031396aca89.png)
![8-programa_42](https://cloud.githubusercontent.com/assets/22351269/23384732/a6a47750-fd11-11e6-9a29-06f2d52ec828.png)
![8-programa_43](https://cloud.githubusercontent.com/assets/22351269/23384733/a6a5ff1c-fd11-11e6-8ad6-b44789813e4d.png)
![8-programa_44](https://cloud.githubusercontent.com/assets/22351269/23384736/a6a9b6a2-fd11-11e6-8d01-600556976b6a.png)
![8-programa_45](https://cloud.githubusercontent.com/assets/22351269/23384735/a6a7b8fc-fd11-11e6-839e-fa0748977fc6.png)
![8-programa_46](https://cloud.githubusercontent.com/assets/22351269/23384737/a6af5404-fd11-11e6-8976-0779ee27350e.png)
![8-programa_47](https://cloud.githubusercontent.com/assets/22351269/23384740/a6c5818e-fd11-11e6-8757-82a1145ad0b2.png)
![8-programa_48](https://cloud.githubusercontent.com/assets/22351269/23384739/a6c4ad72-fd11-11e6-8b07-b91ea051ead2.png)
![8-programa_49](https://cloud.githubusercontent.com/assets/22351269/23384738/a6c19c9a-fd11-11e6-941d-ced23ec283b3.png)
![8-programa_50](https://cloud.githubusercontent.com/assets/22351269/23384741/a6c8eaae-fd11-11e6-82d7-2bb1271da3a2.png)
![8-programa_51](https://cloud.githubusercontent.com/assets/22351269/23384743/a6cf704a-fd11-11e6-8217-5c40c0b88b9c.png)
![8-programa_52](https://cloud.githubusercontent.com/assets/22351269/23384742/a6ce3fea-fd11-11e6-9b7c-fb41e57a0f5a.png)
