### ISSUE TITLE
Agregar menú "Supplier Evaluation"

### ISSUE THREAD

**Issue by fmendoza-gstd** [globalstandards/gpsi-audit-android#10]
## Requerimiento
Se requiere agregar menú "Supplier Evaluation" al drawer.

![415afc2e-fdd0-11e6-851a-62182fc9b1df](https://cloud.githubusercontent.com/assets/22350992/23487544/6cd8e8b6-feac-11e6-806c-425ec103b108.png)

**Comment by gvazquez-gstd** [comment]
![x1](https://cloud.githubusercontent.com/assets/22351269/23765343/867f0a28-04c6-11e7-8093-9609e657d88c.png)

**Comment by fmendoza-gstd** [comment]
## Modificar
@gvazquez-gstd, realizar las siguientes modificaciones:

![867f0a28-04c6-11e7-8093-9609e657d88c](https://cloud.githubusercontent.com/assets/22350992/23767243/8a883f52-04cd-11e7-8977-f169fd4b16f3.png)

**Comment by gvazquez-gstd** [comment]
![x4](https://cloud.githubusercontent.com/assets/22351269/23768048/565f0726-04d0-11e7-8b9f-a1a4370ce27f.png)

**Comment by fmendoza-gstd** [comment]
Good Job! 👍
