### ISSUE TITLE
Diseñar pantalla "Proveedores"

### ISSUE THREAD

**Issue by fmendoza-gstd** [globalstandards/gpsi-audit-android#11]
## Requerimiento
Se requiere el diseño de la pantalla para desplegar listado de proveedores.
Cada elemento de la lista debe desplegar la siguiente información:
1. Nombre
2. Teléfono
3. Email

La pantalla deberá mostrarse cuando el usuario presione la opción "Proveedores" de la sección "Evaluación de proveedores" del menu desplegable.

![565f0726-04d0-11e7-8b9f-a1a4370ce27f](https://cloud.githubusercontent.com/assets/22350992/23806258/98d63014-0586-11e7-820c-f10c1b61b792.png)

**Comment by gvazquez-gstd** [comment]
![1x](https://cloud.githubusercontent.com/assets/22351269/23811196/8f1a7b8e-059a-11e7-9630-a0526f6754db.png)

**Comment by fmendoza-gstd** [comment]
## Modificar
@gvazquez-gstd, realizar las siguientes modificaciones:

![8f1a7b8e-059a-11e7-9630-a0526f6754db](https://cloud.githubusercontent.com/assets/22350992/23815683/d2242a56-05ae-11e7-82a7-0f642b7d8cc2.png)

**Comment by gvazquez-gstd** [comment]
![x1](https://cloud.githubusercontent.com/assets/22351269/23913232/ea0852c2-08a7-11e7-8e45-488250a33362.png)

**Comment by fmendoza-gstd** [comment]
Good Job! 👍
