### ISSUE TITLE
Diseñar pantalla "Usuarios"

### ISSUE THREAD

**Issue by fmendoza-gstd** [globalstandards/gpsi-audit-android#12]
## Requerimiento
Se requiere el diseño de la pantalla para desplegar listado de usuarios.
Cada elemento de la lista debe desplegar la siguiente información:
1. Nombre
2. Email
3. Role
4. Lenguaje

La pantalla deberá mostrarse cuando el usuario presione la opción "Usuarios" de la sección "Configuración" del menu desplegable.

![565f0726-04d0-11e7-8b9f-a1a4370ce27f](https://cloud.githubusercontent.com/assets/22350992/23806448/5aeeb0fe-0587-11e7-8a40-9e919e314fd5.png)

**Comment by gvazquez-gstd** [comment]
![x1](https://cloud.githubusercontent.com/assets/22351269/23911191/a5fd18d4-08a1-11e7-9e97-3e6c4fc35fd8.png)

**Comment by gvazquez-gstd** [comment]
![x3](https://cloud.githubusercontent.com/assets/22351269/23919254/c956e052-08bb-11e7-97a3-f3aed04e1a60.png)

**Comment by fmendoza-gstd** [comment]
Good Job! 👍
