### ISSUE TITLE
Diseñar pantalla "Detalle de Usuario"

### ISSUE THREAD

**Issue by fmendoza-gstd** [globalstandards/gpsi-audit-android#13]
## Requerimiento
Se requiere el diseño de la pantalla para desplegar detalle de usuario, debe mostrar la información que se muestra en la siguiente imagen:

![captura de pantalla 2017-03-10 a las 11 52 42](https://cloud.githubusercontent.com/assets/22350992/23806655/1d414e6e-0588-11e7-823e-eaf2b5cdf117.png)

Ejemplo completo:
![captura de pantalla 2017-03-10 a las 11 49 55](https://cloud.githubusercontent.com/assets/22350992/23806686/36ce3ee6-0588-11e7-9a01-74709c2886c4.png)

**Comment by gvazquez-gstd** [comment]
![x4_1](https://cloud.githubusercontent.com/assets/22351269/23926723/76f48574-08db-11e7-8429-f2736b0caa42.png)
![x4_2](https://cloud.githubusercontent.com/assets/22351269/23926722/76edecd2-08db-11e7-8de5-dcb89365c1de.png)

**Comment by fmendoza-gstd** [comment]
Good Job! 👍
