### ISSUE TITLE
Diseñar pantalla "Detalle de Proveedor"

### ISSUE THREAD

**Issue by fmendoza-gstd** [globalstandards/gpsi-audit-android#14]
## Requerimiento
Se requiere el diseño de la pantalla para desplegar detalle de proveedor, debe mostrar la información que se muestra en la siguiente imagen:

![captura de pantalla 2017-03-10 a las 12 08 30](https://cloud.githubusercontent.com/assets/22350992/23807189/655115ca-058a-11e7-80da-4b9be147c24f.png)

**Comment by gvazquez-gstd** [comment]
![x3](https://cloud.githubusercontent.com/assets/22351269/23817777/5baf2832-05bb-11e7-88d3-968daf2b0d2a.png)
![x4](https://cloud.githubusercontent.com/assets/22351269/23817778/5bb05338-05bb-11e7-88e2-d9e63cbc9e9d.png)

**Comment by fmendoza-gstd** [comment]
## Modificar
@gvazquez-gstd, realizar las siguientes modificaciones al listado de contactos:

![8f1a7b8e-059a-11e7-9630-a0526f6754db](https://cloud.githubusercontent.com/assets/22350992/23815683/d2242a56-05ae-11e7-82a7-0f642b7d8cc2.png)

**Comment by gvazquez-gstd** [comment]
![x1](https://cloud.githubusercontent.com/assets/22351269/23917959/c4e6f084-08b6-11e7-96ee-582eb13291bc.png)

**Comment by gvazquez-gstd** [comment]
![x2_1_2](https://cloud.githubusercontent.com/assets/22351269/23919191/88e21bf4-08bb-11e7-8c88-f87cc7760b47.png)
![x2_1_1](https://cloud.githubusercontent.com/assets/22351269/23919193/88e7728e-08bb-11e7-8087-df98944023ce.png)
![x2_2](https://cloud.githubusercontent.com/assets/22351269/23919192/88e684e6-08bb-11e7-89aa-bc80b7c2b5b4.png)

**Comment by fmendoza-gstd** [comment]
Good Job! 👍
