### ISSUE TITLE
Diseñar pantalla "Nuevo Usuario"

### ISSUE THREAD

**Issue by fmendoza-gstd** [globalstandards/gpsi-audit-android#15]
## Requerimiento
Se requiere el diseño de la pantalla para agregar nuevo usuario, debe mostrar la información que se muestra en la siguiente imagen:

![captura de pantalla 2017-03-10 a las 11 52 42](https://cloud.githubusercontent.com/assets/22350992/23806655/1d414e6e-0588-11e7-823e-eaf2b5cdf117.png)

La pantalla debe mostrarse al presionar el botón "+":

![c956e052-08bb-11e7-97a3-f3aed04e1a60](https://cloud.githubusercontent.com/assets/22350992/23958352/7cd10b70-0967-11e7-8709-e91e0e8dac0d.png)

**Comment by gvazquez-gstd** [comment]
![x1](https://cloud.githubusercontent.com/assets/22351269/23959854/e7c4a9ec-096b-11e7-94d7-153d582604d0.png)
![x2](https://cloud.githubusercontent.com/assets/22351269/23959855/e7c4e6dc-096b-11e7-8e80-f157661be753.png)

**Comment by fmendoza-gstd** [comment]
Good Job! 👍
