### ISSUE TITLE
Diseñar pantalla "Iniciar Sesión"

### ISSUE THREAD

**Issue by fmendoza-gstd** [globalstandards/gpsi-audit-android#2]
Se requiere diseño de pantalla para que usuario pueda iniciar sesión. El diseño deberá de ser parecido a la de la siguiente imagen:

![1-intro](https://cloud.githubusercontent.com/assets/22351269/23384674/a52bdac6-fd11-11e6-8f6c-b6b1516533d7.png)

**Comment by gvazquez-gstd** [comment]
![screenshot_2017-02-28-09-47-36](https://cloud.githubusercontent.com/assets/22351269/23412591/97cd01d6-fd9b-11e6-8363-e1a844b4e03d.png)

**Comment by fmendoza-gstd** [comment]
Good Job 👍
