### ISSUE TITLE
Diseñar pantalla "Crear nueva cuenta"

### ISSUE THREAD

**Issue by fmendoza-gstd** [globalstandards/gpsi-audit-android#3]
Se requiere diseño de pantalla para que usuario pueda crear nueva cuenta. El diseño deberá de ser parecido a la de la siguiente imagen:

![1-intro](https://cloud.githubusercontent.com/assets/22351269/23384673/a5288dda-fd11-11e6-8488-e4fcfd794184.png)

**Comment by gvazquez-gstd** [comment]
![screenshot_2017-02-28-11-10-56](https://cloud.githubusercontent.com/assets/22351269/23415971/a28a9f56-fda6-11e6-9c4a-b440264e9e6b.png)

**Comment by fmendoza-gstd** [comment]
@gvazquez-gstd, realizar las siguientes modificaciones:

**Comment by gvazquez-gstd** [comment]
![screenshot_2017-02-28-15-25-16](https://cloud.githubusercontent.com/assets/22351269/23433914/2fd39ade-fdca-11e6-8c1d-9c31ddd60c7c.png)

**Comment by fmendoza-gstd** [comment]
@gvazquez-gstd, realizar las siguientes modificaciones:

![a28a9f56-fda6-11e6-9c4a-b440264e9e6b](https://cloud.githubusercontent.com/assets/22350992/23435824/0ecebf2c-fdce-11e6-88ba-0b73f5f45bcc.png)

**Comment by gvazquez-gstd** [comment]
![screenshot_2017-02-28-16-14-32](https://cloud.githubusercontent.com/assets/22351269/23436686/0faa6e52-fdd1-11e6-862c-b7946f79417c.png)

**Comment by fmendoza-gstd** [comment]
Good Job 👍
