### ISSUE TITLE
Diseñar pantalla "Principal"

### ISSUE THREAD

**Issue by fmendoza-gstd** [globalstandards/gpsi-audit-android#4]
Se requiere el diseño de la pantalla principal. Seguir las siguientes consideraciones:

1. El diseño deberá de ser similar al siguiente, siga las restricciones
![a5287d90-fd11-11e6-88e2-787b90f26172](https://cloud.githubusercontent.com/assets/22350992/23412918/c956c132-fd9c-11e6-9a44-7d9b8ba91fc1.png)

2. Deberá de aparecer un menu drawer que se mire similar al siguiente:
![android-navigation-drawer-menu](https://cloud.githubusercontent.com/assets/22350992/23412678/fbb404e2-fd9b-11e6-9972-f8716075cc13.png)

**Comment by gvazquez-gstd** [comment]
![screenshot_2017-02-28-15-23-10](https://cloud.githubusercontent.com/assets/22351269/23436457/415afc2e-fdd0-11e6-851a-62182fc9b1df.png)
![screenshot_2017-02-28-15-24-00](https://cloud.githubusercontent.com/assets/22351269/23436458/4166220c-fdd0-11e6-870b-f47af43a2b64.png)

**Comment by fmendoza-gstd** [comment]
@gvazquez-gstd, realizar las siguientes modificaciones:

![4166220c-fdd0-11e6-870b-f47af43a2b64](https://cloud.githubusercontent.com/assets/22350992/23436959/f5d400be-fdd1-11e6-8fd7-e1ccbb2ca83e.png)

**Comment by gvazquez-gstd** [comment]
![screenshot_2017-02-28-17-16-08](https://cloud.githubusercontent.com/assets/22351269/23438916/ba9cc9e2-fdd9-11e6-893e-6a4b00b60b76.png)

**Comment by fmendoza-gstd** [comment]
Good Job 👍
