### ISSUE TITLE
Agregar lista de "Auditorías de Certificación"

### ISSUE THREAD

**Issue by fmendoza-gstd** [globalstandards/gpsi-audit-android#5]
## Requerimiento
Se requiere que sobre la pantalla "Principal" en la sección "Certificaciones" se agregue listado cuyos elementos muestren información resumida de las auditorías de certificación.

Cada elemento de la lista debe mostrar la siguiente información:

1. Ref #: Número de referencia
2. Nombre del auditor lider
3. Fecha de la auditoría
4. Status de la auditoría
5. Standard de la auditoría

![ba9cc9e2-fdd9-11e6-893e-6a4b00b60b76](https://cloud.githubusercontent.com/assets/22350992/23466973/56b03a34-fe62-11e6-9579-60b48bf05fd5.png)

**Comment by gvazquez-gstd** [comment]
![screenshot_2017-03-01-14-55-19](https://cloud.githubusercontent.com/assets/22351269/23480902/33e8f57c-fe8f-11e6-9f20-7628b4eb72f2.png)

**Comment by fmendoza-gstd** [comment]
## Modificar
@gvazquez-gstd, realizar las siguientes modificaciones:

![33e8f57c-fe8f-11e6-9f20-7628b4eb72f2](https://cloud.githubusercontent.com/assets/22350992/23482527/0231ecb8-fe95-11e6-94e5-d4691a338b01.png)

**Comment by gvazquez-gstd** [comment]
![screenshot_2017-03-01-16-26-37](https://cloud.githubusercontent.com/assets/22351269/23484314/1b1a4386-fe9c-11e6-844a-2e2e146d8bb5.png)

**Comment by fmendoza-gstd** [comment]
## Modificar
@gvazquez-gstd, realizar las siguientes modificaciones:

![1b1a4386-fe9c-11e6-844a-2e2e146d8bb5](https://cloud.githubusercontent.com/assets/22350992/23484530/f6287efc-fe9c-11e6-8876-25d6a2c19c75.png)

**Comment by gvazquez-gstd** [comment]
![screenshot_2017-03-01-17-14-18](https://cloud.githubusercontent.com/assets/22351269/23485782/8ba2dcca-fea2-11e6-8e6b-fae959eb702c.png)

**Comment by fmendoza-gstd** [comment]
## Modificar
@gvazquez-gstd, realizar las siguientes modificaciones:

![8ba2dcca-fea2-11e6-8e6b-fae959eb702c](https://cloud.githubusercontent.com/assets/22350992/23485917/469ec76e-fea3-11e6-858f-33a324426dd3.png)

**Comment by gvazquez-gstd** [comment]
![screenshot_2017-03-01-17-51-43](https://cloud.githubusercontent.com/assets/22351269/23486814/e38e4230-fea7-11e6-93d1-01e66f427c49.png)

**Comment by fmendoza-gstd** [comment]
Good Job 👍
