### ISSUE TITLE
Agregar lista de "Auditorías de Proveedor"

### ISSUE THREAD

**Issue by fmendoza-gstd** [globalstandards/gpsi-audit-android#6]
## Requerimiento
Se requiere que sobre la pantalla "Principal" en la sección "Proveedores" se agregue listado cuyos elementos muestren información resumida de las auditorías de proveedor.

Cada elemento de la lista debe mostrar la siguiente información:

1. Ref #: Número de referencia
2. Nombre del proveedor
3. Nombre del auditor lider
4. Fecha de la auditoría
5. Status de la auditoría
6. Nombre del checklist de la auditoría

![56b03a34-fe62-11e6-9579-60b48bf05fd5](https://cloud.githubusercontent.com/assets/22350992/23482929/76bd4090-fe96-11e6-8d7f-918cc85d02df.png)

**Comment by gvazquez-gstd** [comment]
![screenshot_2017-03-01-17-07-06](https://cloud.githubusercontent.com/assets/22351269/23485578/9da92e2a-fea1-11e6-99b0-6e6e9032f0eb.png)

**Comment by fmendoza-gstd** [comment]
## Modificar
@gvazquez-gstd, realizar las siguientes modificaciones:

![9da92e2a-fea1-11e6-99b0-6e6e9032f0eb](https://cloud.githubusercontent.com/assets/22350992/23485943/70035f98-fea3-11e6-883e-271da25bfb70.png)

**Comment by gvazquez-gstd** [comment]
![screenshot_2017-03-01-17-51-51](https://cloud.githubusercontent.com/assets/22351269/23486827/f499cf86-fea7-11e6-87ab-a34ea2c14637.png)

**Comment by fmendoza-gstd** [comment]
Good Job 👍
