### ISSUE TITLE
Agregar botón para agregar auditorías

### ISSUE THREAD

**Issue by fmendoza-gstd** [globalstandards/gpsi-audit-android#7]
## Requerimiento
Se requiere que en la pantalla principal se agregue botón con la intención de que el usuario pueda solicitar auditorías. El botón debe estar presente en la sección "Certificaciones" y "Proveedores".

![ba9cc9e2-fdd9-11e6-893e-6a4b00b60b76](https://cloud.githubusercontent.com/assets/22350992/23486073/18711832-fea4-11e6-897b-9785e2133496.png)

**Comment by gvazquez-gstd** [comment]
![screenshot_2017-03-01-18-06-21](https://cloud.githubusercontent.com/assets/22351269/23487227/4b777b30-feaa-11e6-900f-d170482c6232.png)

**Comment by fmendoza-gstd** [comment]
God Job 👍
