### ISSUE TITLE
Crear pantalla para solicitar auditoría

### ISSUE THREAD

**Issue by fmendoza-gstd** [globalstandards/gpsi-audit-android#8]
## Requerimiento
Se requiere el diseño de la pantalla para solicitar nueva auditoría de proveedor, el formulario debe contener los siguientes elementos:

1. ComboBox para escoger proveedor
2. ComboBox para escoger el checklist
3. Campo para capturar la fecha de la auditoría
4. Campo de texto para capturar notas

El formulario debe aparecer cuando el usuario presiona el botón "+" desde la pantalla principal y la sección de "proveedores".

**Comment by gvazquez-gstd** [comment]
![device-2017-03-08-172711](https://cloud.githubusercontent.com/assets/22351269/23728896/bfc6ca3e-0424-11e7-964d-9958d0e51c58.png)

**Comment by fmendoza-gstd** [comment]
## Modificar
@gvazquez-gstd, realizar las siguientes modificaciones:

![bfc6ca3e-0424-11e7-964d-9958d0e51c58](https://cloud.githubusercontent.com/assets/22350992/23758130/556650b2-04ae-11e7-8c7d-b262c5cc1251.png)

**Comment by gvazquez-gstd** [comment]
![x3](https://cloud.githubusercontent.com/assets/22351269/23767428/1f468cc0-04ce-11e7-92e0-91664f5fd4d2.png)

**Comment by fmendoza-gstd** [comment]
## Modificar
@gvazquez-gstd, realizar las siguientes modificaciones:

![1f468cc0-04ce-11e7-92e0-91664f5fd4d2](https://cloud.githubusercontent.com/assets/22350992/23767931/f6e317c4-04cf-11e7-84e7-40f6f4dd43be.png)

**Comment by gvazquez-gstd** [comment]
![x5](https://cloud.githubusercontent.com/assets/22351269/23770739/df7e4e5a-04d9-11e7-8ab3-521d33460bad.png)

**Comment by fmendoza-gstd** [comment]
## Modificar
@gvazquez-gstd, realizar las siguientes modificaciones:

![df7e4e5a-04d9-11e7-8ab3-521d33460bad](https://cloud.githubusercontent.com/assets/22350992/23800409/ec5f586a-0571-11e7-9ba6-c4926287c661.png)

**Comment by gvazquez-gstd** [comment]
![x7](https://cloud.githubusercontent.com/assets/22351269/23807037/bda9f738-0589-11e7-8a1a-00559c400dd9.png)
![x8](https://cloud.githubusercontent.com/assets/22351269/23807038/bdaaf73c-0589-11e7-9d08-cafd4a9a3747.png)

**Comment by fmendoza-gstd** [comment]
God Job! 👍
