### ISSUE TITLE
Crear pantalla para agregar proveedor

### ISSUE THREAD

**Issue by fmendoza-gstd** [globalstandards/gpsi-audit-android#9]
## Requerimiento
Se requiere pantalla con diseño para crear un nuevo proveedor, el formulario deberá de contener los siguientes campos:

1. Imagen del proveedor
2. Nombre del proveedor
3. Dirección del proveedor:
   1. Calle 1
   2. Calle 2
   3. Ciudad
   4. Estado
   5. Código Postal
   6. País
4. Email
5. Teléfono

El formulario debe aparecer cuando el usuario presiona el submenu "Suppliers" desde el drawer de la pantalla principal.

**Comment by gvazquez-gstd** [comment]
![x2_1](https://cloud.githubusercontent.com/assets/22351269/23766117/2ec8e850-04c9-11e7-9bf0-13ac8e61af95.png)
![x2_2](https://cloud.githubusercontent.com/assets/22351269/23766116/2ebe6696-04c9-11e7-8898-b2201463c4ae.png)

**Comment by fmendoza-gstd** [comment]
## Modificar
@gvazquez-gstd, realizar las siguientes modificaciones:

![2ec8e850-04c9-11e7-9bf0-13ac8e61af95](https://cloud.githubusercontent.com/assets/22350992/23768158/ad61b3e8-04d0-11e7-90a8-50261e1b3d74.png)

![2ebe6696-04c9-11e7-8898-b2201463c4ae](https://cloud.githubusercontent.com/assets/22350992/23768163/afd671a4-04d0-11e7-8e87-cf2eecab9c5e.png)

**Comment by gvazquez-gstd** [comment]
![x6](https://cloud.githubusercontent.com/assets/22351269/23775335/d83f680e-04ed-11e7-98bb-7b685daad5e2.png)

**Comment by fmendoza-gstd** [comment]
Good Job! 👍
